version: '3.8'

services:
  mongo_db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: cart_db
      MONGO_INITDB_ROOT_USERNAME: cart
      MONGO_INITDB_ROOT_PASSWORD: cart123
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  order-service:
    image: damageddream/order-service:latest
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://cart:cart123@mongo_db:27017/cart_db?authSource=admin
      - invoice.api.key=${INVOICE_KEY}
      - aws.accessKeyId=${AWS_KEY}
      - aws.secretKey=${AWS_SECRET}
    ports:
      - "8060:8060"
    depends_on:
      - mongo_db

volumes:
  mongo-data:
    driver: local