name: CICD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: '21'
      - name: Build Project
        run: mvn clean package -DskipTests
      - name: Login to dockerhub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t damageddream/order-service .
      - name: Publish mage to docker hub
        run: docker push damageddream/order-service:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Create .env file
        run: |
          echo "INVOICE_KEY=${{ secrets.INVOICE_KEY }}" > /home/ec2-user/deployment/.env
          echo "AWS_KEY=${{ secrets.AWS_KEY }}" >> /home/ec2-user/deployment/.env
          echo "AWS_SECRET=${{ secrets.AWS_SECRET }}" >> /home/ec2-user/deployment/.env
      - name: Run application and db with docker-compose
        run: |
          cd /home/ec2-user/deployment
          docker-compose down
          docker-compose pull damageddream/order-service:latest
          docker-compose up -d
